pipeline {
    agent any
    tools {
        maven 'MAVEN_HOME'
    }

    environment {
        SONAR_HOST_URL = 'http://localhost:9000'
        SONAR_AUTH_TOKEN = credentials('ham')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Techgirll12/TASK3.git'
                sh 'ls -la'  // List files in the workspace root
            }
        }

        stage('Build') {
            steps {
                dir('TASK3') {  // Navigate to the TASK3 directory
                    sh 'ls -la'  // List files in the TASK3 directory
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('TASK3') {  // Navigate to the TASK3 directory
                    sh 'mvn test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('TASK3') {  // Navigate to the TASK3 directory
                    sh 'mvn verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('TASK3') {  // Navigate to the TASK3 directory
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        mvn sonar:sonar \
                        -Dsonar.projectKey=sample_project10 \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login=$SONAR_AUTH_TOKEN \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                        """
                    }
                }
            }
        }
    }
}
